### ISSUE TITLE
Git conflict resolution headers remains in JSONLs

### ISSUE THREAD

**Issue by vd-omermazig** [NVIDIA/GenerativeAIExamples#212]
Didn't use them yet, but I noticed:

https://github.com/NVIDIA/GenerativeAIExamples/blob/main/nemo/retriever-synthetic-data-generation/scripts/conf/config-nq.yaml
https://github.com/NVIDIA/GenerativeAIExamples/blob/main/nemo/retriever-synthetic-data-generation/scripts/conf/config-fiqa.yaml

Have some git headers that weren't resolved in the main branch:

```
easiness_filter:
  _target_: nemo_retriever_sdg.EasinessFilter
  filter_cfg:
<<<<<<< HEAD
    filter_threshold: 0.75
    embedding_model: "intfloat/e5-large-unsupervised"
=======
    filter_threshold: 0.95
    embedding_model: "BAAI/bge-large-en-v1.5"
>>>>>>> 3d49ef8 (added config-nq and config-fiqa)
    batch_size: 16
```

Which will of course make the jsonl unusable
